# Generated by Django 4.1.3 on 2022-12-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('species', models.CharField(max_length=20)),
                ('type_r', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('origin_name', models.CharField(max_length=100)),
                ('location_name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('episode', models.CharField(max_length=100)),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
