# Generated by Django 4.1.3 on 2022-12-03 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rick_morty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pokemon',
            table='characters',
        ),
    ]
