# Generated by Django 4.1.3 on 2022-12-03 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rick_morty', '0002_alter_pokemon_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pokemon',
            table='db_characters',
        ),
    ]
